### PR TITLE
Add accessibilityLabel/Value to sample charts

### PR DESCRIPTION
**Pull request by mathewa6**
Thanks for creating this project! I've gone ahead and started working on Issue #24 by adding accessibilityLabel and accessibilityValue to Line and the Bar charts that did not have the attributes set.

Before I continue with the other charts, I did want to bring up one difference between the simple and detail views that I think is worth exploring - namely that for the simple charts that are previews, it may not make sense to have VoiceOver users traverse all data points inline. Instead in ```BarChartSimpleOverview``` I manually set the ```accessibilityChartDescriptor``` modifier to only allow audio graph use with the cell label acting as the accessibilityLabel. The detail views continue having the full default SwiftChart accessibility.

Since this is also an example repository that people may copy paste from - I'm not sure of the value of the above differentiation between simple/detail view accessibility. However, I'm happy to make changes either way based on your thoughts and have marked this a draft for now.

### CODE REVIEW

**Comment by jordibruin** [comment]
Great point. I’m not sure what the best practice is for a preview chart in terms of accessibility 🤔 you can use your best judgement for now and we can always change it later if we come up with something better!

**Comment by mathewa6** [comment]
Current accessibility status - separate AXChartDescriptor for Overview charts and full per Mark label/value for Detail charts

(I'm incorporating changes from main branch as well):

- [x] Simple Line chart
- [ ] Line chart with lollipop
- [x] Heartbeat Chart
- [x] Simple Bar chart
- [x] Simple dual bar chart
- [ ] Range Chart
- [ ] Pyramid Chart
- [ ] Area Chart
- [ ] Range with Max and Min Chart
- [x] One dimensional bar
- [ ] Heatmap Block Chart
- [ ] Scatter Chart
- [ ] Heartbeat range Chart
- [ ] Vector Field

**Comment by jordibruin** [comment]
This is lovely @mathewa6. Feel free to submit a PR that is not fully covering everything yet so that it doesn't become too big of a thing for you to finish 🙂

**Comment by mathewa6** [comment]
@jordibruin  Alright - well it was a small hop to get all charts covered and most chart implementation files are untouched except to add the accessibility modifiers and raise the access level of data properties. There are a lot of minor things I'll open new PRs for

- The majority of accessibility changes are visible only in Overview charts (I filed FB10320202 because on DetailCharts, unless you just rebooted your device, the provided label/value are not used, so dates etc sound strange. You can try changing the label but at least for me it defaults to inferred labels)
- Some charts do not verbalize information along axes - I've marked these as FIXME/TODO in comments
- Could probably use some protocol implementation to cleanup especially in ```ChartType``` file

Here's a couple videos showing the different dataset summaries as I scrub/pause over each:

https://user-images.githubusercontent.com/5402357/175085251-7af8df09-41bd-4891-9fea-9100f9f791b0.mov

https://user-images.githubusercontent.com/5402357/175086125-a76b8cb9-38fe-4e41-a1e9-923aebc6f25c.mov


Happy to make cleanup/changes/add comments for clarity etc.

**Comment by mathewa6** [comment]
Updated to add support for UV index and Candlestick charts.

**Comment by mathewa6** [comment]
Updated to work with the .isOverview pattern and add support for LinePlot, GitHubContributions and SoundBars.

It's worth noting that in order to support VoiceOver use with the SoundBars chart I made a few change that are a bit more intrusive than other charts.
- Changed MicrophoneMonitor to be a .recording session instead of (.playAndRecord) and to only start in the SoundBars view vs. as soon as app is started (VoiceOver is "ducked" otherwise)
- Added methods and toggle button to start/stop recording so VoiceOver can pause a recording and study the recorded samples

Given the relatively low PR activity the past couple days, maybe we can consider review/merging at your convenience. @jordibruin

**Comment by jordibruin** [comment]
@mathewa6 thanks for all the work with this. I will have to go through this in a bit more detail, but also don't know all the a11y approaches so let's see what the community can find to improve on your work!

Really happy with this, thanks!!

**Comment by mathewa6** [comment]
@jordibruin absolutely - happy to address any issues you encounter if you tag me in them! I only addressed VoiceOver a11y so there's always more that can be done. 

Thanks for the merge 🥳

**Pull request merged**
